name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: |
          pnpm vite build
          cp ./manifest.json ./dist/manifest.json
          zip -j obsidian-writeaid-plugin-${{ github.ref_name }}.zip ./dist/**
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "obsidian-writeaid-plugin-${{ github.ref_name }}.zip"
          tag: ${{ github.ref_name }}
          draft: false
          prerelease: false
          makeLatest: true
          generateReleaseNotes: true
