name: Validation

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm prettier --check .
      - name: Run ESLint
        run: pnpm eslint . --ext .ts,.svelte
      - name: Build TypeScript
        run: pnpm build
