name: Validation

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier
        id: prettier
        continue-on-error: true
        run: pnpm prettier --check .
      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: pnpm eslint . --ext .ts,.svelte
      - name: Build TypeScript
        id: build
        continue-on-error: true
        run: |
          pnpm build
      - name: Comment PR on Failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prettier_failed = ${{ steps.prettier.outcome == 'failure' }};
            const eslint_failed = ${{ steps.eslint.outcome == 'failure' }};
            const build_failed = ${{ steps.build.outcome == 'failure' }};

            let failureDetails = '## ❌ Validation Failed\n\n';
            failureDetails += '### Failed Checks:\n';

            if (prettier_failed) {
              failureDetails += '- **Prettier**: Code formatting check failed\n';
              failureDetails += '  - Run `pnpm prettier --write .` to fix formatting\n';
            }
            if (eslint_failed) {
              failureDetails += '- **ESLint**: Linting errors found\n';
              failureDetails += '  - Run `pnpm eslint . --ext .ts,.svelte --fix` to auto-fix issues\n';
            }
            if (build_failed) {
              failureDetails += '- **TypeScript Build**: Compilation failed\n';
              failureDetails += '  - Check the build output above for errors\n';
            }

            failureDetails += '\n### Next Steps:\n';
            failureDetails += '1. Review the workflow logs for detailed error messages\n';
            failureDetails += '2. Run the suggested fix commands locally\n';
            failureDetails += '3. Commit and push the fixes\n';
            failureDetails += '4. The workflow will re-run automatically\n';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: failureDetails
            });

      - name: Fail if any step failed
        if: failure()
        run: exit 1
